name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - "8.1"
          - "8.2"

    name: Build - PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup PHP
        uses: shivammathur/setup-php@2.23.0
        with:
          php-version: ${{ matrix.php }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v3.2.3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies (composer)
        run: composer install --prefer-dist

      - name: Check code style (PHP)
        run: ./vendor/bin/pint --test
