name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - "8.0"
        pimcore:
          # - ~10.1.0
          # - ~10.2.0
          # - ~10.3.0
          # - ~10.4.0
          - ~10.5.0
        include:
          - pimcore: ~10.1.0
            template_tag: v10.1.0
          - pimcore: ~10.2.0
            template_tag: v10.1.4
          - pimcore: ~10.3.0
            template_tag: v10.1.9
          - pimcore: ~10.4.0
            template_tag: v10.1.13
          - pimcore: ~10.5.0
            template_tag: v10.2.0

    name: Pimcore ${{ matrix.pimcore }}

    steps:
      - name: Clone Skeleton
        run: git clone -b ${{ matrix.template_tag }} --single-branch --depth 1 https://github.com/pimcore/skeleton.git .

      - uses: actions/checkout@v3.1.0
        with:
          path: packages/pimcore-dump-helper

      - name: Setup PHP
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: ${{ matrix.php }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v3.0.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install local repository
        run: composer config repositories.package_name local packages/pimcore-dump-helper

      - name: Install local package
        run: composer require vintagesucks/pimcore-dump-helper
