name: process-mysqldump

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"

    name: test

    steps:
      - uses: actions/checkout@v3.5.3

      - name: test with file
        run: bin/process-mysqldump test.sql | wc -l | grep 5

      - name: test with stdin
        run: cat test.sql | bin/process-mysqldump | wc -l | grep 5
